### ISSUE TITLE
Checkboxes of certain kind can not be checked

### ISSUE THREAD

**Issue by rohitkhirapate** [altaurog/pdfforms#1]
Here is example fillable form. In Address Ste, Apt,Flr these checkboxes can not be checked as JSON do not have valid option to mark it as checked.
https://www.uscis.gov/sites/default/files/files/form/i-539.pdf

**Comment by altaurog** [comment]
Thanks for reporting this.  The “On” value is padded by a space before and after, which wasn’t handled properly.  The following test data works for me.  I’ve fixed the json generation, but better support for  checkboxes would definitely be nice.
```
i-539.pdf
6,, APT 
8,, FLR 
9,, STE 
13,, STE 
14,, FLR 
15,,Hello
16,, APT 
```
