### ISSUE TITLE
KeyError in .pdf vs .PDF

### ISSUE THREAD

**Issue by khazaddim** [altaurog/pdfforms#13]
![fill](https://user-images.githubusercontent.com/44733891/96401520-9446b200-11a1-11eb-828c-754fda5877f6.PNG)

Need to add .upper() to line 80 to avoid key issues later on.:

fdf_str = generate_fdf(field_defs[filepath.upper()], formdata)

**Comment by altaurog** [comment]
File names are case sensitive.  The names in the csv input must match exactly the names of the pdf files to be filled.

**Comment by khazaddim** [comment]
I had tried both upper and lower case "pdf" in the csv file.  Either it seemed to not be able to find the file or generate_fdf threw a key error.

**Comment by altaurog** [comment]
If filepath.upper() works, the whole filename should be uppercase, not just the extension.  Look inside the `fields.json` file that is generated by the first step and copy the filenames as they appear there.

**Comment by altaurog** [comment]
Closing this for now, if you still have a problem with latest release, feel free to re-open with more details.
