### ISSUE TITLE
Change text size of filled fields

### ISSUE THREAD

**Issue by georgeamccarthy** [altaurog/pdfforms#15]
Is there a way to change the text size of filled fields? I can't see a line in pdfforms.py where this could be configured. Have you any ideas as to how this could be achieved?

Thanks

**Comment by altaurog** [comment]
Thanks for you interest in the project, @georgeamccarthy!  I have not looked into this at all.  I always assumed this is a property of the pdf file itself, not the field data.  In any case, it is somewhat out of the scope of this project.  Please do report back here though if you find any further information of interest, I am curious to learn more.
(P.S. I had a physics teacher in high school named Mr. McCarthy, he also ran the astronomy club in which I was active)
