### ISSUE TITLE
Form field co-ordinate extraction capability?

### ISSUE THREAD

**Issue by AIMLAPP** [altaurog/pdfforms#17]
Hello,

I am able to extract the form field names, state option and field value of the editable PDFs. This really works wonders!

Along with form field names, state option (for buttons) and field value, would it be possible as well to extract the co-ordinates of each form field (including the radio buttons with multiple tickboxes and state options) using "pdfforms"?

Examples of multiple tickbox and state options with the same form field name can be found here on page 2 (Mr, Mrs, Miss etc):
https://drive.google.com/file/d/1ZsEvbgGrcGhL_9xbXyIsEBQdyEFXzFpT/view?usp=sharing

**Comment by altaurog** [comment]
Thanks for your interest in pdfforms!  This would be a really useful feature, but AFAIK it isn’t supported by pdftk.  Would you like to submit a pull request with an alternative implementation?

**Comment by altaurog** [comment]
Great idea but not currently in scope.  Please open a PR if you would like to suggest an easy approach.
