### ISSUE TITLE
Why not read json?

### ISSUE THREAD

**Issue by shufps** [altaurog/pdfforms#19]
I love this tool, but I'm wondering (a looooot) why it inspects an PDF and saves a json but this json-file can't be used for filling out an PDF.

Should be quite trivial to extract field number and value of the json into a csv-file that is then fed into pdftk.

Is there a special reason to this?

**Comment by altaurog** [comment]
The purpose of the project is filling out a pdf from a familiar format which can be easily manipulated by any user, which json is not.  The json file is part of the implementation, not the interface.

Nonetheless, I am preparing a new version which will give much more flexibility and should address your concerns.

**Comment by shufps** [comment]
Understood :)

Also, I think I don't understand for what the parameter is used:

https://github.com/altaurog/pdfforms/blob/master/pdfforms/pdfforms.py#L158

Why is the default the `fields.json` which can't be used for the `fill`? :dizzy_face:
