### ISSUE TITLE
Can't fill up checkbox

### ISSUE THREAD

**Issue by HarshitDaftary** [altaurog/pdfforms#4]
The library is able to detect checkbox and radio buttons but not able to select - deselect them. Can you please guide me on how to implement that?

**Comment by altaurog** [comment]
Thanks for your interest in pdfforms!  I know the instructions aren’t so clear.  I hope to rewrite them soon.  For now, I’ll just work through an example to demonstrate.  Let’s say we want to check the "Single" filing status box on [f1040.pdf](https://www.irs.gov/pub/irs-pdf/f1040.pdf).

The command `pdfforms inspect f1040.pdf` generates `fields.json` and `test/f1040.pdf`.   Judging from the field numbers in the test pdf, I see it is somewhere between 14 and 20.  Then I look in `fields.json` for those field numbers.  The names there aren’t so meaningful, but it’s clear that 15 and 16 are a pair, so I assume those are the two "Presidential Election Campaign" boxes.  The box we want should be the next one, so we look at the entry for 17, which includes `"stateoption": ["1", "Off"]`.  So to check the box, we want to set 17 to "1".  The csv input should look like this:

f1040.pdf | name | data
-------------|--------|--------
17 | Single | 1

The raw csv file looks like this:
```
f1040.pdf,name,data
17,Single,1
```
Then I run that back through the tool with `pdfforms fill data.csv`

**Comment by HarshitDaftary** [comment]
Thanks that worked.
