### ISSUE TITLE
How to fill drop down value

### ISSUE THREAD

**Issue by HarshitDaftary** [altaurog/pdfforms#5]
The json is able to detect drop down control, but don’t know how to fill value there. Please guide me. Thanks

**Comment by altaurog** [comment]
I don’t have any experience with this.  Can you provide a sample pdf?

**Comment by HarshitDaftary** [comment]
Sorry for late response. 
[sample.pdf](https://github.com/altaurog/pdfforms/files/2596722/sample.pdf)
Please find attached sample pdf document. 
Thanks.

**Comment by HarshitDaftary** [comment]
Hi, Sometimes values are shown in JSON file for textbox but can't be seen on PDF and also can't fill data programmatically on those fields. Can you guide me how to solve that ?

**Comment by altaurog** [comment]
Hi @HarshitDaftary sorry I haven’t had time to look at this yet.  Apparently [additional data must be stored in the fdf](https://stackoverflow.com/q/3558216) to fill a dropdown.  If so, pdfforms does not (yet) support this.  If you’d like to try to get it working, I’ll happily accept a pull request!  (have a look at `fdf_fields`).
