### ISSUE TITLE
How to integrate into a script?

### ISSUE THREAD

**Issue by lukkesweet** [altaurog/pdfforms#8]
How do I integrate this package into a script?  I'm using Python 3.6 installed through Anaconda 3.5 and when I try to integrate it I get the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-126-be479e3e2a7e> in <module>
----> 1 pdfforms.fill('C:/Users/User/Desktop/filldat.csv')

AttributeError: module 'pdfforms' has no attribute 'fill'
```

Also, is there a way to change the name of the file that is filled?

**Comment by altaurog** [comment]
You will have to simulate a cli call by constructing an argparse.Namespace object.  You could do something like this:

```
args = pdfforms.parse_cli(['fill', 'C:/Users/User/Desktop/filldat.csv'])
args.func(args)
```
It would be nice if `main()` would allow argv injection, I suppose.

**Comment by altaurog** [comment]
I just updated `main()`.  This is not a new release; pull the code from github.  Now you can do the following:
```
import glob
from pdfforms.pdfforms import main
main(['inspect'] + glob.glob('f1040*.pdf'))
main(['fill', 'filldat.csv'])
```

**Comment by lukkesweet** [comment]
Thanks! It works great!  Is there anyway to change the name of the output file so I can fill it several times?

**Comment by altaurog** [comment]
Use the `--prefix` option

**Comment by chibbi30j1** [comment]
Can we not use it with the console functions in the scriptor? For example, the below is a list of available functions when the module is imported into Spyder.


FUNCTIONS

    fdf_fields(fields, data)
    
    fill_form(input_path, fdf, output_path, flatten)
    
    fill_forms(path_func, field_defs, data, flatten=True)
    
    fill_pdfs(args)
    
    generate_fdf(fields, data)
    
    generate_test_data(pdf_files, field_defs)
    
    inspect_pdf_fields(form_name)
    
    inspect_pdfs(args)
    
    load_field_defs(defs_file)
    
    main(argv=None)
    
    make_path(prefix)
    
    parse_cli(*args)
    
    read_data(instream)

**Comment by altaurog** [comment]
@chibbi30j1 it wasn’t designed for use like that; this is a cli utility, not a library of console functions.  You are welcome to use it as a library, but I cannot provide direct support for that beyond what you have above.
